apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from sqlalchemy.exc import SQLAlchemyError, IntegrityError
from flask_dance.consumer.storage.sqla import OAuthConsumerMixin

from apps import db, login_manager
from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'users'

    id            = db.Column(db.Integer, primary_key=True)
    username      = db.Column(db.String(64), unique=True)
    email         = db.Column(db.String(64), unique=True)
    password      = db.Column(db.LargeBinary)
    bio           = db.Column(db.Text(), nullable=True)

    oauth_github  = db.Column(db.String(100), nullable=True)
    oauth_google  = db.Column(db.String(100), nullable=True)

    readonly_fields = ["id", "username", "email", "oauth_github", "oauth_google"]

    #__PROFILE_FIELDS__

    #__PROFILE_FIELDS__END
    
    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)

    @classmethod
    def find_by_email(cls, email: str) -> "Users":
        return cls.query.filter_by(email=email).first()

    @classmethod
    def find_by_username(cls, username: str) -> "Users":
        return cls.query.filter_by(username=username).first()
    
    @classmethod
    def find_by_id(cls, _id: int) -> "Users":
        return cls.query.filter_by(id=_id).first()
   
    def save(self) -> None:
        try:
            db.session.add(self)
            db.session.commit()
          
        except SQLAlchemyError as e:
            db.session.rollback()
            db.session.close()
            error = str(e.__dict__['orig'])
            raise IntegrityError(error, 422)
    
    def delete_from_db(self) -> None:
        try:
            db.session.delete(self)
            db.session.commit()
        except SQLAlchemyError as e:
            db.session.rollback()
            db.session.close()
            error = str(e.__dict__['orig'])
            raise IntegrityError(error, 422)
        return

@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

class OAuth(OAuthConsumerMixin, db.Model):
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="cascade"), nullable=False)
    user = db.relationship(Users)

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration

class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)
from flask_dance.contrib.github import github
from flask_dance.contrib.google import google

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users
from apps.config import Config

from apps.authentication.util import verify_pass

# Login & Registration

@blueprint.route("/github")
def login_github():
    """ Github login """
    if not github.authorized:
        return redirect(url_for("github.login"))

    res = github.get("/user")
    return redirect(url_for('home_blueprint.index'))


@blueprint.route("/google")
def login_google():
    """ Google login """
    if not google.authorized:
        return redirect(url_for("google.login"))

    res = google.get("/oauth2/v1/userinfo")
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        user_id  = request.form['username'] # we can have here username OR email
        password = request.form['password']

        # Locate user
        user = Users.find_by_username(user_id)

        # if user not found
        if not user:

            user = Users.find_by_email(user_id)

            if not user:
                return render_template( 'authentication/login.html',
                                        msg='Unknown User or Email',
                                        form=login_form)

        # Check the password
        if verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('home_blueprint.index'))

        # Something (user or pass) is not ok
        return render_template('authentication/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('authentication/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('authentication/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('authentication/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        # Delete user from session
        logout_user()

        return render_template('authentication/register.html',
                               msg='User created successfully.',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('authentication/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home_blueprint.index'))

# Errors

@blueprint.context_processor
def has_github():
    return {'has_github': bool(Config.GITHUB_ID) and bool(Config.GITHUB_SECRET)}

@blueprint.context_processor
def has_google():
    return {'has_google': bool(Config.GOOGLE_ID) and bool(Config.GOOGLE_SECRET)}

@login_manager.unauthorized_handler
def unauthorized_handler():
    return redirect('/login')

templates/authentication/login.html
{% extends "layouts/base-auth.html" %}

{% block title %}Login{% endblock title %}

{% block content %}

  <div class="auth-main">
    <div class="auth-wrapper v1">
      <div class="auth-form">
        <div class="position-relative my-5">
          <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
          </div>
          <div class="card mb-0">
            <form method="post" class="card-body">
              {{ form.hidden_tag() }}

              <div class="text-center">
                <a href="{{ url_for('home_blueprint.index') }}">
                  <div>
                    <img src="{{ url_for('static', filename='assets/images/logo-dark.svg') }}" alt="img">
                  </div>
                </a>
              </div>
              
              <div class="d-flex justify-content-center align-items-center gap-2">
                {% if has_github %}
                <div class="text-center mt-4">
                  <a href="{{ url_for('github.login') }}" style="cursor: pointer;" class="d-inline-block p-2 rounded border text-secondary">
                    <span class="pc-micon">
                      <i data-feather="github"></i>
                    </span>
                  </a>
                </div>
                {% endif %}
  
                {% if has_google %}
                <div class="text-center mt-4">
                  <a href="{{ url_for('google.login') }}" style="cursor: pointer;" class="d-inline-block p-2 rounded border text-secondary">
                    <span class="pc-micon">
                      <i class="fab fa-google"></i>
                    </span>
                  </a>
                </div>
                {% endif %}
              </div>

              <h4 class="text-center f-w-500 mt-4 mb-3">Login</h4>
              <p class="text-center">
                Default account: <strong>test / pass</strong>
              </p>  

              {% if msg %}
                <span class="d-block text-danger mb-3">{{ msg | safe }}</span>
              {% endif %} 

              <div class="form-group mb-3">
                {{ form.username(placeholder="Username or eMail", class="form-control") }}
              </div>
              <div class="form-group mb-3">
                {{ form.password(placeholder="Password", class="form-control", type="password") }}
              </div>

              <div class="d-flex mt-1 justify-content-between align-items-center">
                <div class="form-check">
                  <input class="form-check-input input-primary" type="checkbox" id="customCheckc1" checked="">
                  <label class="form-check-label text-muted" for="customCheckc1">Remember me?</label>
                </div>
                <a href="#" class="text-secondary f-w-400 mb-0">Forgot Password?</a>
              </div>
              <div class="text-center mt-4">
                <button type="submit" name="login" class="btn btn-primary shadow px-sm-4">Login</button>
              </div>
              <div class="d-flex justify-content-center align-items-end mt-4">
                <a href="{{ url_for('authentication_blueprint.register') }}" class="link-primary">Create Account</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/authentication/register.html
{% extends "layouts/base-auth.html" %}

{% block title %}Register{% endblock title %}

{% block content %}

  <div class="auth-main">
    <div class="auth-wrapper v1">
      <div class="auth-form">
        <div class="position-relative my-5">
          <div class="auth-bg">
            <span class="r"></span>
            <span class="r s"></span>
            <span class="r s"></span>
            <span class="r"></span>
          </div>
          <div class="card mb-0">
            
            {% if success %}
            <div class="text-center">
              <span class="d-block text-primary mt-4 mb-2">{{ msg | safe }}</span>
              <br />
              <a href="{{ url_for('authentication_blueprint.login') }}" class="btn btn-primary shadow-2 mb-4">Sign IN</a>
            </div>              
            {% else %}
           
            <form method="post" class="card-body">
              {{ form.hidden_tag() }}
              
              <div class="text-center">
                <a href="{{ url_for('home_blueprint.index') }}">
                  <div>
                    <img src="{{ url_for('static', filename='assets/images/logo-dark.svg') }}" alt="img">
                  </div>
                </a>
              </div>

              {% if has_github %}
              <div class="text-center mt-4">
                <a href="{{ url_for('github.login') }}" style="cursor: pointer;" class="d-inline-block p-2 rounded border text-secondary">
                  <span class="pc-micon">
                    <i data-feather="github"></i>
                  </span>
                </a>
              </div>
              {% endif %}
              
              <h4 class="text-center f-w-500 mt-4 mb-3">Sign up</h4>

              {% if msg %}
              <div class="text-center">
                <span class="d-block text-danger mb-3">{{ msg | safe }}</span>
              </div>  
              {% endif %}  
              
              <div class="form-group mb-3">
                {{ form.username(placeholder="Username", class="form-control") }}
              </div>
              <div class="form-group mb-3">
                {{ form.email(placeholder="Email", class="input form-control", type="email") }}
              </div>
              <div class="form-group mb-3">
                {{ form.password(placeholder="Password", class="form-control", type="password") }}
              </div>

              <div class="d-flex mt-1 justify-content-between">
                <div class="form-check">
                  <input class="form-check-input input-primary" type="checkbox" id="customCheckc1" checked="">
                  <label class="form-check-label text-muted" for="customCheckc1">I agree to all the Terms & Condition</label>
                </div>
              </div>
              <div class="text-center mt-4">
                <button type="submit" name="register" class="btn btn-primary shadow px-sm-4">Sign up</button>
              </div>
              <div class="d-flex justify-content-center align-items-end mt-4">
                <a href="{{ url_for('authentication_blueprint.login') }}" class="link-primary">Login</a>
              </div>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}